redis:
  build:
   redis
  ports:
    - "6999:6379"
  container_name:
    redis

mongo:
  build:
    mongo
  ports:
    - "27017:27017"
  container_name:
    mongo
  

appserver:
  build:
    databox-app-server
  ports:
    - "8091:8091"
  links:
    - mongo
  command:
    /root/start.sh
  container_name:
    app-server

mock-datasource:
  build:
    databox-datasource-mock
  command:
    /root/start.sh
  container_name:
    mock-datasource 
