FROM databox/red-base
MAINTAINER Tom Lodge <tlodge@gmail.com>
RUN cd /usr/lib/node_modules/node-red/nodes && git clone https://github.com/tlodge/databox-nodered-nodes.git databox
#RUN cd /root/node-red/nodes && git clone https://github.com/tlodge/databox-nodered-nodes.git databox 
